### ISSUE TITLE
Поддержка в ide?

### ISSUE THREAD

**Issue by alekstar79** [ksimka/intl_dtpg#6]
Собственно говоря это не является критичным вопросом, но хотелось бы. Т.е. расширение установилось, php подцепил его и работает, а вот storm не понимает, что появился новый класс IntlDateTimePatternGenerator. Кто-нибудь знает как ему объяснить об этом?

**Comment by ksimka** [comment]
Как и в случае с другими расширениями, добавляющими внутренние классы, можно просто добавить stub-файл. Собственно, полезно добавить такой файлик в репо, пожалуй.

**Comment by alekstar79** [comment]
А можно немного по подробнее? Я честно признаюсь не сталкивался с этим. Как эту заглушку написать - просто создать класс с методом (пустым, без имплементации)? И затем, где его прописать? Если конечно я все правильно понял...

**Comment by alekstar79** [comment]
Все разобрался вопросов нет...

**Comment by ksimka** [comment]
Если запилили себе, можете сделать PR сюда с готовым файликом, другим будет полезно.

**Comment by alekstar79** [comment]
> Если запилили себе, можете сделать PR сюда с готовым файликом, другим будет полезно.

Я внимание не обратил, и написал сам файл, а по факту он имеется в проекте [intl_dtpg.stub.php](https://github.com/ksimka/intl_dtpg/blob/master/intl_dtpg.stub.php) Так что в этом нет необходимости...

**Comment by ksimka** [comment]
Оуч, а я и забыл уже :)

**Comment by alekstar79** [comment]
Бывает :) это не беда, у меня тоже не понятно куда глаза глядели? Я заметил его только сейчас, когда читал твой коммент на счет пулреквеста. Взглянул еще раз на репозиторий и улыбнулся. Вот только наверное стоит в readme добавить пару слов об этом.
