### ISSUE TITLE
Merge this into intl extension?

### ISSUE THREAD

**Issue by gharlan** [ksimka/intl_dtpg#7]
Are there any plans to propose this implementation to php-src?
Would be really cool! :)

**Comment by staabm** [comment]
had the same in mind after reading the project readme

**Comment by Shadowmad** [comment]
would like to bump this question

**Comment by ksimka** [comment]
Hi! I'm not sure I have enough energy and motivation to make a proper PR to php-src now, sorry. But feel free to DIY if you want :)

**Comment by gharlan** [comment]
There is [`IntlDatePatternGenerator `](https://www.php.net/manual/de/class.intldatepatterngenerator.php) since PHP 8.1.
